[
    [
        [],
        ["Got to start drawing consistently agin."],
        [],
        [],
        [],
        [],
        [],
        ["Fish shaped ethyl benzene."],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        []
    ],
    [
        ["Lame...."],
        [],
        ["You, but with testicles aflame."],
        [],
        ["thats really ashame."],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        ["Cincinnati bound for the Reds game!", "At this rate, I'd be late for this game."]
    ]
]